#!/usr/bin/env ruby
# frozen_string_literal: true

# Turns locales/*.yml into write/i18n.js, so the app can be a directory of
# static files with no YAML parser and no build step at load time.
#
#   ruby write/build-i18n.rb
#
# The YAML files stay the source of truth -- same as in blog.sh, and the
# same reason: a translator edits text, not JavaScript. Run this after
# changing them; the generated file is committed so that deploying the app
# means copying a directory, nothing more.

require 'yaml'
require 'json'

# The app directory itself: locales/ and the generated i18n.js are both
# in here, so the whole writer is one directory that can be copied.
ROOT = __dir__
FALLBACK = 'en'

locales = {}
Dir[File.join(ROOT, 'locales', '*.yml')].sort.each do |path|
  code = File.basename(path, '.yml')
  data = YAML.safe_load_file(path) || {}
  locales[code] = data
end

abort "locales/#{FALLBACK}.yml is missing -- it is the fallback" unless locales.key?(FALLBACK)

# Every key of the fallback must exist somewhere, or a reader whose locale
# is incomplete sees a raw key like "app.send" in the middle of a sentence.
# Reported rather than fixed: a missing translation is a translator's job,
# and filling it in silently with English would hide that it is missing.
def flatten(hash, prefix = nil)
  hash.flat_map do |key, value|
    full = [prefix, key].compact.join('.')
    value.is_a?(Hash) ? flatten(value, full) : [full]
  end
end

base = flatten(locales[FALLBACK])
locales.each do |code, data|
  next if code == FALLBACK

  missing = base - flatten(data)
  warn "#{code}: #{missing.size} key(s) fall back to #{FALLBACK}: #{missing.join(', ')}" unless missing.empty?
end

out = File.join(ROOT, 'i18n.js')
File.write(out, <<~JS)
  // Generated by write/build-i18n.rb from write/locales/*.yml -- do not edit.
  // Edit the YAML and run the script again.
  window.I18N = #{JSON.pretty_generate(locales)};
  window.I18N_FALLBACK = #{FALLBACK.inspect};
JS
puts "#{out}: #{locales.keys.sort.join(', ')} (#{base.size} keys)"
